secrets:
    sops:
        age_key: ENC[AES256_GCM,data:2NFUhq9+S5jhTwnW6X4Oyl6zyknhzurAL5OmaExX3ukxqdJR/QHklEx04lMn4JMWnPGVMF+1gVYrSuPXjLMJslhm6I8ds8gi+s9G,iv:J7z/QB9TGbbmJ18cYAZeyq0KY+oDDobk0c7N/n5BRbk=,tag:zR5TBDRRYpriewY2AfDWjQ==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:P+ggu7dCnjRxxfoi0JCMeXJs9wy6psPiQg==,iv:qSWKBboYbH9PDSCQzyTH8WT5w0CmrgWjaYvBTU72qDo=,tag:iu6sJOslE9Oa7EIrsrezgQ==,type:str]
            username: ENC[AES256_GCM,data:30LQ4zvnDzSVE1eKEGPCG6Zv4X8zEo9fkg==,iv:w9op00v87cfqw1SiPtGlrvPI2ou7JGummfV1Ok94VMY=,tag:Tk86nCinXL47Nk9XKYkVIw==,type:str]
            password: ENC[AES256_GCM,data:lcqMXxvVjEuxpZ6gm2w=,iv:3KWKqgzVLSZwDyLQza+JOoKuOZOPwPQ5dKIlwpguFqo=,tag:8V9Qohtbw0rJdjkDeDgwKg==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:fHHVxRs5HprWKpU=,iv:dXUuUloEEldPAM+2u5ypFvTB40oOt+mfw0BgKfJtsN0=,tag:2nsDtDQgx0URI4PMwXhdfQ==,type:str]
                password: ENC[AES256_GCM,data:PgCLZmcWLjVf+FlL3zwfm5WDxeRFuHLIeegHjfCBSGb+lipu24bI6Q==,iv:R9vg1u5Pq37E7LCCIfIyJ4Cp6gOsG7fPQvvgSPfX2UA=,tag:XD3biBxFMDrRBNM4fgCZ9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRlI3UG9YTzVncTlubXRs
            QlFEMHpVcUdEdkhWVDV1UjFvSTVtOXlxZDBFCnNiRGdsUWxKS1oralFsVFBGWjgv
            NVlIRldNU292ZGlZdlRHUjl0NnMvaHcKLS0tIHNwVm9XcGVoMjZPYXVqdzhkMHJQ
            RDZkOWkxMDR5dlArK2cxK2NGRWNxb0kKlUb/GgqaZ2uXic8vhP2WyL2bwgOSyO9m
            3fAwoa6K8rBnZO/dG2yHiatwLnpq6bIJV4/U/fGIkYkBZgJs3pgX2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T07:06:16Z"
    mac: ENC[AES256_GCM,data:dztnvssS25tePDtnG/yj+/XoKfIYp5xuZn/VgU6NHRfDfOqIW+abIYeef38TSzSXu0wB7MJoLsoiE1/z7fD7yLBYgAw/dRs37G33tpjGLsY2QJNRe9JuVCQs8HUz51V+56izeCPQ1fki+23nFDCglBUczZXj5uwbye5leSVIJ4I=,iv:JIYmnjK1cVD7CjbuE7Rb+unGBFTnczbirAw6OKNfBP8=,tag:cMx1rEI+TsqC9fmxJb8Gsg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
